import type { Metadata } from "next";
import { Inter, Lexend_Deca } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "700"],
});

const lexend = Lexend_Deca({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Stats Preview Card Component",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${lexend.className} text-[15px] antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
